export const VOLUNTEER_API_ERROR_CODES = [
  'INVALID_REQUEST',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'VALIDATION_ERROR',
  'INVALID_PARAMETER',
  'VOLUNTEER_APPLICATION_ALREADY_PENDING',
  'VOLUNTEER_MEMBER_ALREADY_EXISTS',
  'VOLUNTEER_APPLICATION_NOT_EDITABLE',
  'VOLUNTEER_APPLICATION_ALREADY_EXISTS',
  'VOLUNTEER_APPLICATION_INVALID_STATE',
  'VOLUNTEER_EVENT_CAPACITY_FULL',
  'VOLUNTEER_EVENT_NOT_AVAILABLE',
  'VOLUNTEER_EVENT_NOT_OPEN',
  'VOLUNTEER_RECRUITMENT_CLOSED',
  'VOLUNTEER_TIME_CONFLICT',
  'VOLUNTEER_CANCEL_DEADLINE_EXPIRED',
  'VOLUNTEER_MEMBER_NOT_ACTIVE',
  'VOLUNTEER_PARTICIPATION_ALREADY_EXISTS',
  'VOLUNTEER_PARTICIPATION_DUPLICATE',
  'VOLUNTEER_PARTICIPATION_NOT_FOUND',
  'VOLUNTEER_CAPACITY_BELOW_CURRENT_PARTICIPANTS',
  'VOLUNTEER_EVENT_INVALID_STATE',
] as const

export type VolunteerApiErrorCode =
  (typeof VOLUNTEER_API_ERROR_CODES)[number]

export const VOLUNTEER_API_ERROR_MESSAGE = {
  INVALID_REQUEST: '입력값을 확인해 주세요.',
  UNAUTHORIZED: '로그인이 필요합니다.',
  FORBIDDEN: '이 작업을 수행할 권한이 없습니다.',
  NOT_FOUND: '요청한 정보를 찾을 수 없습니다.',
  VALIDATION_ERROR: '입력값을 확인해 주세요.',
  INVALID_PARAMETER: '요청 값을 확인해 주세요.',
  VOLUNTEER_APPLICATION_ALREADY_PENDING: '이미 처리 중인 가입 신청이 있습니다.',
  VOLUNTEER_MEMBER_ALREADY_EXISTS: '이미 봉사단원으로 등록되어 있습니다.',
  VOLUNTEER_APPLICATION_NOT_EDITABLE: '현재 상태에서는 가입 신청을 변경할 수 없습니다.',
  VOLUNTEER_APPLICATION_ALREADY_EXISTS: '이미 처리 중이거나 승인된 가입 신청이 있습니다.',
  VOLUNTEER_APPLICATION_INVALID_STATE: '현재 상태에서는 가입 신청을 변경할 수 없습니다.',
  VOLUNTEER_EVENT_CAPACITY_FULL: '봉사 모집 인원이 마감되었습니다.',
  VOLUNTEER_EVENT_NOT_AVAILABLE: '현재 참여할 수 없는 봉사 일정입니다.',
  VOLUNTEER_EVENT_NOT_OPEN: '모집 중인 봉사 일정만 신청할 수 있습니다.',
  VOLUNTEER_RECRUITMENT_CLOSED: '봉사 모집이 마감되었습니다.',
  VOLUNTEER_TIME_CONFLICT: '같은 시간대에 신청한 봉사 일정이 있습니다.',
  VOLUNTEER_CANCEL_DEADLINE_EXPIRED:
    '취소 가능 시간이 지났습니다. 관리자에게 문의해 주세요.',
  VOLUNTEER_MEMBER_NOT_ACTIVE:
    '현재 봉사 일정에 참여할 수 없는 상태입니다. 관리자에게 문의해 주세요.',
  VOLUNTEER_PARTICIPATION_ALREADY_EXISTS: '이미 신청한 봉사 일정입니다.',
  VOLUNTEER_PARTICIPATION_DUPLICATE: '이미 신청한 봉사 일정입니다.',
  VOLUNTEER_PARTICIPATION_NOT_FOUND: '참여 신청 내역을 찾을 수 없습니다.',
  VOLUNTEER_CAPACITY_BELOW_CURRENT_PARTICIPANTS:
    '현재 참여 인원보다 모집 인원을 적게 설정할 수 없습니다.',
  VOLUNTEER_EVENT_INVALID_STATE: '현재 상태에서는 일정을 변경할 수 없습니다.',
} as const satisfies Record<VolunteerApiErrorCode, string>
